# -*- coding: utf-8 -*-
"""meetingminitesgenaretor.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cfpjWlpuTkzdWKNZK-JbLpie07IJwt_a
"""

import pandas as pd
from datetime import datetime
print("MEETING MINUTES GENERATOR\n")
meeting_tittle=input("Enter meeting title:")
date=input("Enter meeting date (DD-MM-YYYY):")
time=input("enter meeting time :")
participants=input("Enter participants (comma separated):")
agenda=input("Enter agenda (comma separated):")
decisions=input("Enter decision taken (comma separated):")
action_times=input("Enter action_time (comma separated):")
preapred_by=input("prepared by:")
participants_list=[p.strip() for p in participants.split(",") if p.strip()]
agenda_list=[a.strip() for a in agenda.split(",") if a.strip()]
decisions_list=[d.strip() for d in decisions.split(",") if d.strip()]
action_lists=[a.strip() for a in action_times.split(",") if a.strip()]
minutes={
    "meeting_tittle":meeting_tittle,
    "date":date,
    "time":time,
    "participants":";".join(participants_list),
    "agenda":";".join(agenda_list),
    "decisions taken":";".join(decisions_list),
    "action_times":";".join(action_lists),
    "prepared_by":preapred_by,
    "Genearted_at":datetime.now().strftime("%Y-%m-%d %H:%M:%S")
}
df=pd.DataFrame(list(minutes.jitems()), columns=["Field","Details"])
print("\n Meeting Generated Successfully\n")
display(df)
df.to_csv(f"{meeting_tittle}.csv",index=False)
print("\n File savedas meeting_minutes.csv")

