# -*- coding: utf-8 -*-
"""reviews.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14RidCi2KBhc4L3ZRltklzXkj_ScLVtRC
"""

!pip install transformers torch pandas
from transformers import pipeline
import pandas as pd

sentiment = pipeline("sentiment-analysis")
reviews="""THe laptop starts quickly and works smoothly for dialy tasks.
THE SCREEN QUALITY IS CLEAR AND FOR WATCHING VIDEOS.
Battery back up is average and needs charging often.
The fan makes noise when many apps are running.
Overal , it is a good laptop for gaming.
"""

sentences= reviews.split(".")
pros=[]
cons=[]
for s in sentences:
  s=s.strip()
  if s=="":
    continue
  result=sentiment(s)[0]
  if result["label"]=="POSITIVE":
    pros.append(s)
  elif result["label"]=="NEGATIVE":
    cons.append(s)
pros=pros[:2]
cons=cons[:2]
df=pd.DataFrame({
    "pros":pros,
    "cons":cons
})
print(df,end="->")

