# -*- coding: utf-8 -*-
"""SENTENCE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m3zsIVYThmxw9npRc7NLwNmRhYxkCeWO
"""

!pip install sentence-transformers

from sentence_transformers import SentenceTransformer,util
model = SentenceTransformer('all-MiniLM-L6-v2')
text1=input("enter text 1: ")
text2=input("enter text 2: ")
embedding1=model.encode(text1)
embedding2=model.encode(text2)
similarity=util.cos_sim(embedding1,embedding2)
print("\n similarity score:",round(float(similarity),2))
if similarity >0.75:
  print("Similarity level : High")
elif similarity >0.75:
  print("Similarity level : medium")
else :
  print("Similarity level : low")

