# -*- coding: utf-8 -*-
"""textgenerationcode.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13hL4VHYVZZ1B-r6gRbkLPlSccGyRouhg
"""

!pip install transformers torch

from transformers import pipeline
generator = pipeline(
    "text-generation",
    model ="gpt2"
)
prompt="Artificial Intelligence in finance will"
result=generator(prompt,max_length=50,num_return_sequences=1)
print("Ai generated text")
print(result[0]['generated_text'])