# -*- coding: utf-8 -*-
"""timetable.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TZ1kX3Ro0MipWlB7VNs84AMNdqtrIbkY
"""

import pandas as pd
import random

print("TIMETABLE GENERATOR\n")
subject_input=input("enter subjects (comma separated):")
days_input=input("enter days (comma separated):")
periods_per_day=int(input("enter noof periods per day:"))
subjects=[s.strip() for s in subject_input.split(",")if s.strip()]
days=[d.strip() for d in days_input.split(",")if d.strip()]
if len(subjects)==0 or len(days)==0:
  print("invalid input. Please try again")
else:
  timetable={}
  for day in days:
    timetable[day]=random.choices(subjects,k=periods_per_day)
  df=pd.DataFrame(timetable)
  df.index=[f"period {i+1}" for i in range(periods_per_day)]
  print("\n TimeTable Generated Successfully\n")
  display(df)
  df.to_csv("TimeTable.csv")
  print("\n TimeTable saved as timetable.csv")